"""Add detailed JobDescription fields

Revision ID: 31295eea0121
Revises: b5cf7d37898e
Create Date: 2026-06-30 17:38:19.076699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31295eea0121'
down_revision: Union[str, Sequence[str], None] = 'b5cf7d37898e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('preferred_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('salary', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('technologies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'technologies')
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'salary')
    op.drop_column('jobs', 'preferred_skills')
    # ### end Alembic commands ###
