"""Add job matching detailed schema

Revision ID: b5cf7d37898e
Revises: 050eaab660d7
Create Date: 2026-06-30 16:09:30.790627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cf7d37898e'
down_revision: Union[str, Sequence[str], None] = '050eaab660d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('detailed_analysis_json', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('company', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('education', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'education')
    op.drop_column('jobs', 'experience')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('jobs', 'company')
    op.drop_column('job_matches', 'detailed_analysis_json')
    # ### end Alembic commands ###
